# Generated by Django 5.1.8 on 2026-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_homepagecontent_hero_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
