# Generated by Django 5.1.8 on 2026-05-19 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('MIN_PRODUCT_QUANTITY', 'Minimum Product Quantity'), ('SHIPPING_DISCOUNT', 'Shipping Discount'), ('CART_TOTAL_DISCOUNT', 'Cart Total Discount'), ('FIRST_TIME_USER', 'First Time User'), ('USER_SPECIFIC', 'User Specific')], db_index=True, default='PRODUCT_DISCOUNT', max_length=25)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5)),
                ('min_quantity_required', models.PositiveIntegerField(default=1, help_text='Minimum quantity required to apply coupon')),
                ('min_cart_total', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required for CART_TOTAL_DISCOUNT', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used. Leave blank for unlimited.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Coupon becomes valid from this date and time')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Coupon expiration date and time')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Display name for the rule', max_length=150)),
                ('threshold_amount', models.DecimalField(decimal_places=2, help_text='Minimum order amount required for free shipping', max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Free Shipping Rule',
                'verbose_name_plural': 'Free Shipping Rules',
                'ordering': ['-threshold_amount'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cart_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before shipping and discounts', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking number for order tracking', max_length=100, null=True)),
                ('customer_name', models.CharField(help_text='Required customer name', max_length=100)),
                ('customer_email', models.EmailField(db_index=True, help_text='Required customer email', max_length=254)),
                ('customer_phone', models.CharField(help_text='Required customer phone number', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_account_number', models.CharField(help_text='Required backend-set account number', max_length=50)),
                ('sender_number', models.CharField(help_text="Required customer's payment number", max_length=50)),
                ('transaction_id', models.CharField(help_text='Required transaction/Reference ID', max_length=100)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text="e.g., 'Package has left the warehouse.'", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., By Air, By Ship, Door to Door', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price (used if no tiers defined)', max_digits=10)),
                ('delivery_estimated_time', models.CharField(blank=True, help_text="e.g., '1-2 days', '5-7 days', '2-3 weeks'", max_length=50, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight this shipping method can handle (in kg). Leave blank for no weight limit.', max_digits=10, null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity this shipping method can handle. Leave blank for no quantity limit.', null=True)),
                ('preferred_pricing_type', models.CharField(choices=[('quantity', 'Quantity-based'), ('weight', 'Weight-based')], default='quantity', help_text='Preferred pricing method for this shipping method', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Minimum quantity required for this pricing tier (for quantity-based pricing)', null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity for this pricing tier (leave empty for unlimited)', null=True)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight in kg required for this pricing tier (for weight-based pricing)', max_digits=8, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in kg for this pricing tier (leave empty for unlimited)', max_digits=8, null=True)),
                ('pricing_type', models.CharField(choices=[('quantity', 'Quantity-based'), ('weight', 'Weight-based')], default='quantity', help_text='Whether this tier is based on quantity or weight', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this tier', max_digits=10)),
                ('has_incremental_pricing', models.BooleanField(default=False, help_text='Enable incremental pricing for weights/quantities above the minimum')),
                ('increment_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Additional cost per unit (kg for weight, item for quantity) above minimum', max_digits=10, null=True)),
                ('increment_unit_size', models.DecimalField(decimal_places=2, default=1.0, help_text='Size of each increment unit (e.g., 0.5 for every 0.5kg, 1.0 for every 1kg)', max_digits=8)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority tiers will be selected first when multiple tiers match')),
            ],
            options={
                'verbose_name': 'Shipping Tier',
                'verbose_name_plural': 'Shipping Tiers',
                'ordering': ['pricing_type', 'priority', 'min_quantity', 'min_weight'],
            },
        ),
    ]
