# Generated by Django 5.1.8 on 2026-05-19 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='eligible_users',
            field=models.ManyToManyField(blank=True, help_text='Users eligible for USER_SPECIFIC coupons', related_name='specific_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freeshippingrule',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='Shipping categories this rule applies to. Leave blank for all categories.', to='products.shippingcategory'),
        ),
        migrations.AddField(
            model_name='freeshippingrule',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='free_shipping_rules', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='shipping_categories',
            field=models.ManyToManyField(blank=True, help_text='Shipping categories this method is available for', related_name='allowed_shipping_methods', to='products.shippingcategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, help_text='Shipping method', null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.shippingmethod'),
        ),
        migrations.AddField(
            model_name='shippingtier',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tiers', to='orders.shippingmethod'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'active'], name='coupon_code_active_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['active', 'expires_at'], name='coupon_active_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orderitem_order_product_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-ordered_at'], name='order_ordered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-ordered_at'], name='order_user_ordered_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-ordered_at'], name='order_status_ordered_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email', '-ordered_at'], name='order_email_ordered_idx'),
        ),
    ]
