# Generated by Django 5.1.8 on 2026-06-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_city_order_delivery_slot_label_and_more'),
        ('products', '0006_product_category_alter_product_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeshippingrule',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='Shipping categories this rule applies to. Leave blank for all categories.', to='products.category'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='shipping_categories',
            field=models.ManyToManyField(blank=True, help_text='Shipping categories this method is available for', related_name='allowed_shipping_methods', to='products.category'),
        ),
    ]
