# Generated by Django 5.1.8 on 2026-05-19 07:54

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='e.g., Nike, Apple, Samsung', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Brand logo image', null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True, help_text='Brief description of the brand')),
                ('website', models.URLField(blank=True, help_text='Official brand website')),
                ('slug', models.SlugField(help_text='URL-friendly brand name', unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this brand is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Red, Ocean Blue', max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='e.g., #FF0000', max_length=7, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAdditionalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional_images/')),
            ],
            options={
                'verbose_name_plural': 'Product Additional Images',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Material, Weight (Not for Color or Size)', max_length=255)),
                ('value', models.CharField(help_text='e.g., Cotton, 250g', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Electronics, Fragile Items, Heavy Items', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what types of products belong to this category')),
            ],
            options={
                'verbose_name': 'Shipping Category',
                'verbose_name_plural': 'Shipping Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., S, M, L, XL, 42', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryMinimumOrderQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(help_text='Minimum quantity required for wholesale orders in this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(help_text='Category for which minimum order quantity applies', on_delete=django.db.models.deletion.CASCADE, related_name='minimum_order_quantity', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Minimum Order Quantity',
                'verbose_name_plural': 'Category Minimum Order Quantities',
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special price for wholesale orders (leave empty if not applicable)', max_digits=10, null=True)),
                ('minimum_purchase', models.PositiveIntegerField(default=1, help_text='Minimum quantity required for wholesale orders. Admin can set different values per product (e.g., Mobile=10, Laptop=5, Fashion=60)')),
                ('affiliate_commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage for affiliates (e.g., 5.00 for 5%)', max_digits=5, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=8, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Product brand', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='products.color')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
