# Generated by Django 5.1.8 on 2026-05-20 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_name_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='Promo label (NEW, ORGANIC)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_color',
            field=models.CharField(blank=True, help_text='Tailwind CSS classes or hex for badge', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text='Country/region of origin', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='Display unit (e.g., "per kg", "6-pack")', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_unit',
            field=models.CharField(blank=True, help_text='Wholesale unit (e.g., "per case")', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
