# Generated by Django 5.1.8 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_freeshippingrule_applicable_categories_and_more'),
        ('products', '0006_product_category_alter_product_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_category',
            field=models.ForeignKey(blank=True, help_text='Determines which shipping methods are available for this product', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_category_products', to='products.category'),
        ),
        migrations.DeleteModel(
            name='ShippingCategory',
        ),
    ]
