# Generated by Django 5.1.8 on 2026-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_dayoffrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
