# Generated by Django 5.1.8 on 2026-07-02 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staffprofile_staff_id'),
        ('stores', '0007_store_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffshift',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_shifts', to='stores.store'),
        ),
    ]
