# Generated by Django 5.1.8 on 2026-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_staffshift_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
