# Generated by Django 6.0.4 on 2026-05-05 05:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=150)),
                ('full_address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=30)),
                ('open_time', models.CharField(help_text='24-hour HH:MM e.g. 08:00', max_length=5)),
                ('close_time', models.CharField(help_text='24-hour HH:MM e.g. 21:00', max_length=5)),
                ('hours', models.CharField(help_text='Display label e.g. 08:30 — 21:00', max_length=30)),
                ('map_link', models.URLField(blank=True, help_text='Paste full Google Maps URL — lat/lng auto-extracted on save')),
                ('lat', models.FloatField(blank=True, help_text='Auto-filled from Map Link', null=True)),
                ('lng', models.FloatField(blank=True, help_text='Auto-filled from Map Link', null=True)),
                ('image', models.URLField(help_text='Banner image URL')),
                ('provenance', models.CharField(help_text='e.g. from Almería', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeftoverPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftover_packs', to='stores.store')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='stores.store')),
            ],
            options={
                'ordering': ['order', 'category'],
                'unique_together': {('store', 'category')},
            },
        ),
        migrations.CreateModel(
            name='StoreFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('leftoverPack', 'Leftover Pack'), ('organic', 'Organic'), ('delivery', 'Delivery'), ('pickup', 'Click & Collect'), ('clickCollect', 'Click & Collect')], max_length=30)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'feature')},
            },
        ),
    ]
