# Generated by Django 6.0.4 on 2026-05-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='map_link',
            field=models.URLField(blank=True, help_text='Full বা শর্ট Google Maps URL — lat/lng auto-extracted on save'),
        ),
    ]
