# Generated by Django 6.0.4 on 2026-05-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='store show order wise'),
        ),
    ]
