# Generated by Django 6.0.4 on 2026-05-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeavailability',
            name='icon',
            field=models.CharField(blank=True, default='shopping-basket', help_text='Lucide icon name in kebab-case, e.g. apple, leaf, wheat, milk, wine, croissant', max_length=80),
        ),
        migrations.AlterField(
            model_name='leftoverpack',
            name='image',
            field=models.ImageField(help_text='Pack image — upload JPG/PNG/WebP', upload_to='stores/leftover-packs/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='close_time',
            field=models.TimeField(help_text='Closing time (use AM/PM picker)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='hours',
            field=models.CharField(blank=True, editable=False, help_text='Auto-calculated from open/close time — e.g. 8:00 AM — 9:00 PM', max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(help_text='Banner image — upload JPG/PNG/WebP', upload_to='stores/banners/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_time',
            field=models.TimeField(help_text='Opening time (use AM/PM picker)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Store display order'),
        ),
        migrations.AlterField(
            model_name='store',
            name='provenance',
            field=models.CharField(blank=True, default='', help_text='e.g. from Almería (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='storeavailability',
            name='category',
            field=models.CharField(help_text='e.g. Fruits, Veg, Bread', max_length=80),
        ),
    ]
