# Generated by Django 5.1.8 on 2026-06-07 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storeavailability_icon_alter_leftoverpack_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leftoverpack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='estimated_delivery',
            field=models.CharField(blank=True, help_text='e.g., 1-2 Business Days', max_length=150),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='package_type',
            field=models.CharField(choices=[('KG', 'KG'), ('Box', 'Box'), ('Bundle', 'Bundle'), ('Carton', 'Carton'), ('Piece', 'Piece'), ('Sack', 'Sack'), ('Other', 'Other')], default='Box', max_length=50),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='leftoverpack',
            name='weight_quantity',
            field=models.CharField(blank=True, help_text='e.g., 5 KG, 2 Boxes', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Store Owner for managing leftover packs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leftoverpack',
            name='image',
            field=models.ImageField(help_text='Main Pack image — upload JPG/PNG/WebP', upload_to='stores/leftover-packs/'),
        ),
        migrations.AlterField(
            model_name='leftoverpack',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='LeftoverPackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stores/leftover-packs/gallery/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.leftoverpack')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
