# Generated by Django 5.1.8 on 2026-07-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_leftoverpack_shipping_category_leftoverpack_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_code',
            field=models.CharField(blank=True, help_text='Unique Store ID', max_length=50, null=True, unique=True),
        ),
    ]
