# Generated by Django 6.0.4 on 2026-05-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_wholesaleuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleuser',
            name='profile_image',
        ),
    ]
