# Generated by Django 6.0.4 on 2026-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_remove_wholesaleuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='wholesale/avatars/'),
        ),
    ]
