# Generated by Django 5.1.8 on 2026-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0005_wholesalebenefit_wholesalecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleuser',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
