# Generated by Django 5.1.8 on 2026-05-19 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('WHOLESALER', 'Wholesaler'), ('VENDOR', 'Vendor'), ('AFFILIATE', 'Affiliate'), ('ADMIN', 'Admin')], db_index=True, default='CUSTOMER', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, verbose_name='State / Province / Region')),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(help_text='Unique referral code for affiliate marketing', max_length=20, unique=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Admin approval status for affiliate account', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this affiliate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_affiliates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate Profile',
                'verbose_name_plural': 'Affiliate Profiles',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('PRODUCT_DELETED', 'Product Deleted'), ('VENDOR_REGISTERED', 'Vendor Registered'), ('TICKET_CREATED', 'Ticket Created'), ('ORDER_PLACED', 'Order Placed')], db_index=True, max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Mobile number (e.g., 01XXXXXXXXX)', max_length=20)),
                ('alt_phone', models.CharField(blank=True, help_text='Alternative phone number', max_length=20, null=True)),
                ('address_line', models.CharField(help_text='Street address / Area', max_length=255)),
                ('city', models.CharField(help_text='City / District', max_length=100)),
                ('division', models.CharField(choices=[('dhaka', 'Dhaka (ঢাকা)'), ('chittagong', 'Chittagong (চট্টগ্রাম)'), ('rajshahi', 'Rajshahi (রাজশাহী)'), ('khulna', 'Khulna (খুলনা)'), ('barisal', 'Barisal (বরিশাল)'), ('sylhet', 'Sylhet (সিলেট)'), ('rangpur', 'Rangpur (রংপুর)'), ('mymensingh', 'Mymensingh (ময়মনসিংহ)')], help_text='Division', max_length=20)),
                ('postal_code', models.CharField(blank=True, help_text='Postal / ZIP code', max_length=10, null=True)),
                ('business_name', models.CharField(help_text='Registered business name', max_length=255)),
                ('business_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship (একমালিকানা)'), ('partnership', 'Partnership (অংশীদারি)'), ('limited_company', 'Private Limited Company (প্রাইভেট লিমিটেড)'), ('public_limited', 'Public Limited Company'), ('cooperative', 'Cooperative Society'), ('other', 'Other')], default='sole_proprietorship', max_length=30)),
                ('business_description', models.TextField(blank=True, help_text='Describe your business and products', null=True)),
                ('business_domain', models.URLField(blank=True, help_text='Business website URL (optional)', null=True)),
                ('business_logo', models.ImageField(help_text='Business logo (required)', upload_to='vendors/logos/')),
                ('business_banner', models.ImageField(blank=True, help_text='Business banner image', null=True, upload_to='vendors/banners/')),
                ('trade_license', models.FileField(help_text='Trade license document', upload_to='vendors/trade_licenses/')),
                ('trade_license_number', models.CharField(blank=True, help_text='Trade license number', max_length=100, null=True)),
                ('tin_certificate', models.FileField(blank=True, help_text='TIN certificate (optional)', null=True, upload_to='vendors/tin/')),
                ('tin_number', models.CharField(blank=True, help_text='TIN number', max_length=50, null=True)),
                ('nid_front', models.FileField(help_text='National ID card front side', upload_to='vendors/nid/')),
                ('nid_back', models.FileField(help_text='National ID card back side', upload_to='vendors/nid/')),
                ('nid_number', models.CharField(help_text='National ID number', max_length=20)),
                ('bin_number', models.CharField(blank=True, help_text='BIN number (for VAT registered businesses)', max_length=50, null=True)),
                ('bank_statement', models.FileField(blank=True, help_text='Recent bank statement (optional)', null=True, upload_to='vendors/bank/')),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, help_text='Account holder name', max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch name', max_length=100, null=True)),
                ('bank_routing_number', models.CharField(blank=True, help_text='Routing number', max_length=20, null=True)),
                ('mobile_banking_number', models.CharField(blank=True, help_text='bKash / Nagad / Rocket number', max_length=20, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=12)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (admin use)', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
            },
        ),
        migrations.CreateModel(
            name='VendorTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('TECHNICAL', 'Technical'), ('PAYMENT', 'Payment'), ('ACCOUNT', 'Account'), ('ORDER', 'Order'), ('PRODUCT', 'Product')], default='GENERAL', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=15)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_tickets', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Ticket',
                'verbose_name_plural': 'Vendor Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesalerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Legal business name', max_length=255)),
                ('business_type', models.CharField(blank=True, help_text='Type of business (e.g., Import/Export, Retail, Manufacturing)', max_length=100, null=True)),
                ('trade_license', models.FileField(help_text='Upload trade license or business registration document', upload_to='wholesaler/trade_licenses/')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Admin approval status for wholesaler account', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this wholesaler', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wholesalers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wholesaler Profile',
                'verbose_name_plural': 'Wholesaler Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='user_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='user_date_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='address_user_default_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['approval_status', 'created_at'], name='vendor_status_created_idx'),
        ),
    ]
