# Generated by Django 5.1.8 on 2026-05-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_leftover_packs',
            field=models.BooleanField(default=False, help_text='Notify on leftover pack deals'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_order_updates',
            field=models.BooleanField(default=True, help_text='Notify on order status changes'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_price_changes',
            field=models.BooleanField(default=True, help_text='Notify when product price changes'),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_promotions',
            field=models.BooleanField(default=True, help_text='Receive promotional emails'),
        ),
    ]
